### ISSUE TITLE
Games Being Added To "No Platform" (dev branch)

### ISSUE THREAD

**Issue by crunchprank** [Clidus/gwl#68]
Despite adding the games to my collection and checking off the platforms I own them for, they are shown on my profile and activity as "No Platform"

Screen cap: http://i.imgur.com/qt01mut.png

For the above example, I actually added that specific game to two different platforms.

I've used your most recent `database.txt` file from https://github.com/Clidus/gwl/issues/67

**Comment by Clidus** [comment]
Nice find. You should be a tester :)

Bug seems to have been caused by me concating all the javascript files together. The checkbox on change event has been hijacked by the on change event that is supposed to only happen on the collection page (you see the reference to a filter). 

Will need a bit of reworking.

![screen shot 2015-06-20 at 21 42 20](https://cloud.githubusercontent.com/assets/3776029/8269144/44dfd356-1795-11e5-9132-9a1face676e5.png)

**Comment by crunchprank** [comment]
Once again, I appreciate you looking into this! :)

**Comment by Clidus** [comment]
Sorry for the delay. For now I've scoped the checkbox on change bindings so they don't conflict. Longer term, the filter code is all going to be removed anyway.

**Comment by crunchprank** [comment]
Verified working. No worries about the delay. Thanks.
