### ISSUE TITLE
Issue With Updating

### ISSUE THREAD

**Issue by crunchprank** [Clidus/gwl#87]
Hello again, Clidus!

So I recently decided to perform an update on the platform since you've been making some great changes to it. Everything went pretty smoothly, and the site looks fine. I can log into my account and post blogs, etc.

However whenever I go to search for a game, I get the following error:

```
Error Number: 1146

Table 'cpnet_gamedb.apiLog' doesn't exist

INSERT INTO `apiLog` (`Url`, `RequestType`, `Result`, `Processed`, `DateStamp`) VALUES ('http://www.giantbomb.com/api/search/?api_key=editedAPIkey&format=json&resources=game&limit=10&page=1&query=fallout+4', 'Search', '{\"error\":\"OK\",\"limit\":10,\"offset\":0,\"number_of_page_results\":10,\"number_of_total_results\":694,\"status_code\":1,\"results\":[{\"aliases\":null,\"api_detail_url\":\"http:\\/\\/www.giantbomb.com\\/api\\/game\\/3030-49833\\/\",\"date_added\":\"2015-06-03 05:38:47\",\"date_last_updated\":\"2015-11-09 16:59:47\",\"deck\":\"The Fallout series continues in a post-apocalyptic Boston, Massachusetts.\",\"description\":\"
```

I'm using the database schema from your previous release, and maybe something has changed since then due to the error I see: `Table 'cpnet_gamedb.apiLog' doesn't exist`.

I'm curious if there's anything that you see that might be causing this and what I could do to rectify it. Normally I wouldn't mind starting from scratch, however I've been heavily using this the past month and would prefer not to start from scratch :) Anyway, let me know if you need any additional information from myself! Thanks again for working on such an awesome platform.

**Comment by Clidus** [comment]
Hey ya,

It looks like you're missing the apiLog table. :)

The database schema has changed since you first pulled the project. If you take a look at the history of database.txt, you can see what changes you need to make to your database. You shouldn't need to start from scratch.

https://github.com/Clidus/gwl/commits/master/database.txt

You'll be missing a couple new tables (`apiLog` and `gamePlatforms`), and some new fields (such as `PasswordResetValidUntil` on the users table).

**Comment by crunchprank** [comment]
Okay cool, I'll look through the database.txt file and try and apply the new changes to my current tables. Thanks!

**Comment by Clidus** [comment]
No problem!
